// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: authenticator.proto

package authenticator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticatorExport_OtpType int32

const (
	AuthenticatorExport_OTP_INVALID AuthenticatorExport_OtpType = 0
	AuthenticatorExport_OTP_HOTP    AuthenticatorExport_OtpType = 1
	AuthenticatorExport_OTP_TOTP    AuthenticatorExport_OtpType = 2
)

// Enum value maps for AuthenticatorExport_OtpType.
var (
	AuthenticatorExport_OtpType_name = map[int32]string{
		0: "OTP_INVALID",
		1: "OTP_HOTP",
		2: "OTP_TOTP",
	}
	AuthenticatorExport_OtpType_value = map[string]int32{
		"OTP_INVALID": 0,
		"OTP_HOTP":    1,
		"OTP_TOTP":    2,
	}
)

func (x AuthenticatorExport_OtpType) Enum() *AuthenticatorExport_OtpType {
	p := new(AuthenticatorExport_OtpType)
	*p = x
	return p
}

func (x AuthenticatorExport_OtpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticatorExport_OtpType) Descriptor() protoreflect.EnumDescriptor {
	return file_authenticator_proto_enumTypes[0].Descriptor()
}

func (AuthenticatorExport_OtpType) Type() protoreflect.EnumType {
	return &file_authenticator_proto_enumTypes[0]
}

func (x AuthenticatorExport_OtpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticatorExport_OtpType.Descriptor instead.
func (AuthenticatorExport_OtpType) EnumDescriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{0, 0}
}

type AuthenticatorExport_OtpAlgo int32

const (
	AuthenticatorExport_ALGO_INVALID AuthenticatorExport_OtpAlgo = 0
	AuthenticatorExport_SHA1         AuthenticatorExport_OtpAlgo = 1
)

// Enum value maps for AuthenticatorExport_OtpAlgo.
var (
	AuthenticatorExport_OtpAlgo_name = map[int32]string{
		0: "ALGO_INVALID",
		1: "SHA1",
	}
	AuthenticatorExport_OtpAlgo_value = map[string]int32{
		"ALGO_INVALID": 0,
		"SHA1":         1,
	}
)

func (x AuthenticatorExport_OtpAlgo) Enum() *AuthenticatorExport_OtpAlgo {
	p := new(AuthenticatorExport_OtpAlgo)
	*p = x
	return p
}

func (x AuthenticatorExport_OtpAlgo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticatorExport_OtpAlgo) Descriptor() protoreflect.EnumDescriptor {
	return file_authenticator_proto_enumTypes[1].Descriptor()
}

func (AuthenticatorExport_OtpAlgo) Type() protoreflect.EnumType {
	return &file_authenticator_proto_enumTypes[1]
}

func (x AuthenticatorExport_OtpAlgo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthenticatorExport_OtpAlgo.Descriptor instead.
func (AuthenticatorExport_OtpAlgo) EnumDescriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{0, 1}
}

type AuthenticatorExport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Otp     []*AuthenticatorExport_Otp `protobuf:"bytes,1,rep,name=otp,proto3" json:"otp,omitempty"`
	Version int32                      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Size    int32                      `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Index   int32                      `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Id      int32                      `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AuthenticatorExport) Reset() {
	*x = AuthenticatorExport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authenticator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticatorExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatorExport) ProtoMessage() {}

func (x *AuthenticatorExport) ProtoReflect() protoreflect.Message {
	mi := &file_authenticator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatorExport.ProtoReflect.Descriptor instead.
func (*AuthenticatorExport) Descriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticatorExport) GetOtp() []*AuthenticatorExport_Otp {
	if x != nil {
		return x.Otp
	}
	return nil
}

func (x *AuthenticatorExport) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AuthenticatorExport) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AuthenticatorExport) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AuthenticatorExport) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AuthenticatorExport_Otp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret  []byte                      `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Name    string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Issuer  string                      `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Algo    AuthenticatorExport_OtpAlgo `protobuf:"varint,4,opt,name=algo,proto3,enum=main.AuthenticatorExport_OtpAlgo" json:"algo,omitempty"`
	Digits  int32                       `protobuf:"varint,5,opt,name=digits,proto3" json:"digits,omitempty"`
	Type    AuthenticatorExport_OtpType `protobuf:"varint,6,opt,name=type,proto3,enum=main.AuthenticatorExport_OtpType" json:"type,omitempty"`
	Counter int64                       `protobuf:"varint,7,opt,name=counter,proto3" json:"counter,omitempty"`
}

func (x *AuthenticatorExport_Otp) Reset() {
	*x = AuthenticatorExport_Otp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authenticator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthenticatorExport_Otp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatorExport_Otp) ProtoMessage() {}

func (x *AuthenticatorExport_Otp) ProtoReflect() protoreflect.Message {
	mi := &file_authenticator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatorExport_Otp.ProtoReflect.Descriptor instead.
func (*AuthenticatorExport_Otp) Descriptor() ([]byte, []int) {
	return file_authenticator_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AuthenticatorExport_Otp) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *AuthenticatorExport_Otp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthenticatorExport_Otp) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AuthenticatorExport_Otp) GetAlgo() AuthenticatorExport_OtpAlgo {
	if x != nil {
		return x.Algo
	}
	return AuthenticatorExport_ALGO_INVALID
}

func (x *AuthenticatorExport_Otp) GetDigits() int32 {
	if x != nil {
		return x.Digits
	}
	return 0
}

func (x *AuthenticatorExport_Otp) GetType() AuthenticatorExport_OtpType {
	if x != nil {
		return x.Type
	}
	return AuthenticatorExport_OTP_INVALID
}

func (x *AuthenticatorExport_Otp) GetCounter() int64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

var File_authenticator_proto protoreflect.FileDescriptor

var file_authenticator_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xe5, 0x03, 0x0a, 0x13,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x2f, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x4f, 0x74, 0x70, 0x52,
	0x03, 0x6f, 0x74, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x1a, 0xe9, 0x01, 0x0a, 0x03, 0x4f, 0x74, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x04, 0x61, 0x6c, 0x67, 0x6f, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x4f, 0x74,
	0x70, 0x41, 0x6c, 0x67, 0x6f, 0x52, 0x04, 0x61, 0x6c, 0x67, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x69, 0x67, 0x69, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x69, 0x67,
	0x69, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x21, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x4f, 0x74, 0x70,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x07, 0x4f, 0x74, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0f, 0x0a, 0x0b, 0x4f, 0x54, 0x50, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x54, 0x50, 0x5f, 0x48, 0x4f, 0x54, 0x50, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x4f, 0x54, 0x50, 0x5f, 0x54, 0x4f, 0x54, 0x50, 0x10, 0x02, 0x22, 0x25, 0x0a, 0x07,
	0x4f, 0x74, 0x70, 0x41, 0x6c, 0x67, 0x6f, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x4c, 0x47, 0x4f, 0x5f,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x48, 0x41,
	0x31, 0x10, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_authenticator_proto_rawDescOnce sync.Once
	file_authenticator_proto_rawDescData = file_authenticator_proto_rawDesc
)

func file_authenticator_proto_rawDescGZIP() []byte {
	file_authenticator_proto_rawDescOnce.Do(func() {
		file_authenticator_proto_rawDescData = protoimpl.X.CompressGZIP(file_authenticator_proto_rawDescData)
	})
	return file_authenticator_proto_rawDescData
}

var file_authenticator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_authenticator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authenticator_proto_goTypes = []interface{}{
	(AuthenticatorExport_OtpType)(0), // 0: main.AuthenticatorExport.OtpType
	(AuthenticatorExport_OtpAlgo)(0), // 1: main.AuthenticatorExport.OtpAlgo
	(*AuthenticatorExport)(nil),      // 2: main.AuthenticatorExport
	(*AuthenticatorExport_Otp)(nil),  // 3: main.AuthenticatorExport.Otp
}
var file_authenticator_proto_depIdxs = []int32{
	3, // 0: main.AuthenticatorExport.otp:type_name -> main.AuthenticatorExport.Otp
	1, // 1: main.AuthenticatorExport.Otp.algo:type_name -> main.AuthenticatorExport.OtpAlgo
	0, // 2: main.AuthenticatorExport.Otp.type:type_name -> main.AuthenticatorExport.OtpType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_authenticator_proto_init() }
func file_authenticator_proto_init() {
	if File_authenticator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authenticator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticatorExport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authenticator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthenticatorExport_Otp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authenticator_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authenticator_proto_goTypes,
		DependencyIndexes: file_authenticator_proto_depIdxs,
		EnumInfos:         file_authenticator_proto_enumTypes,
		MessageInfos:      file_authenticator_proto_msgTypes,
	}.Build()
	File_authenticator_proto = out.File
	file_authenticator_proto_rawDesc = nil
	file_authenticator_proto_goTypes = nil
	file_authenticator_proto_depIdxs = nil
}
